
name: debug

on:
  workflow_dispatch:
    inputs:
      debug_enabled:
        description: 'Run the build with tmate debugging enabled'     
        required: false
        default: false

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Fetch all history for all tags and branches
      run: |
        git fetch --prune
    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1

    - name: Write Fullkey.snk
      uses: RollyPeres/base64-to-path@v1
      with:
        filePath: ${{ github.workspace }}/src/fullkey.snk
        encodedString: ${{ secrets.SIGNKEY }}

    # Enable tmate debugging of manually-triggered workflows if the input option was provided
    - name: Setup tmate session
      uses: mxschmitt/action-tmate@v3
      # if: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.debug_enabled }}
      with:
       limit-access-to-actor: true
      # timeout-minutes: 10

    - name: Restore
      working-directory: src
      run: |
        dotnet restore --disable-parallel
    - name: Only Build
      if: "github.event.release.prerelease"
      working-directory: src
      run: |
        msbuild XAMLMarkupExtensions.csproj -verbosity:minimal /p:Configuration=Release
    - name: Build & Publish
      if: "!github.event.release.prerelease"
      working-directory: src
      run: |
        msbuild XAMLMarkupExtensions.csproj -verbosity:minimal /p:Configuration=Release /property:NugetAPIKey=${{ secrets.NugetAPIKey }}
    - name: Get Name of Nuget
      working-directory: src/bin/Release/
      env:
        ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
      shell: powershell
      run: |
        Get-ChildItem -Path *.nupkg  | ForEach-Object {Write-Output "::set-env name=NUPKG::$($_.Name)"}

